### ISSUE TITLE
Roadmap Ideas

### ISSUE THREAD

**Issue by albertschulz** [thibaultCha/TCBlobDownload#27]
What do you think about:
1) pause/resume downloads
2) possibility to download files using an ios 7 background task? helpful for very large files when you don't want to have the app open all the time

**Comment by thibaultCha** [comment]
> 2) possibility to download files using an ios 7 background task? helpful for very large files when you don't want to have the app open all the time

If you are still interested, I am currently developing [TCBlobDownloadSwift](https://github.com/thibaultCha/TCBlobDownloadSwift/tree/master) which is using `NSURLSession` for iOS 7+

**Comment by matteocrippa** [comment]
Hey @thibaultCha  feel free to PR here once finished the swift version!

https://github.com/matteocrippa/awesome-swift

**Comment by thibaultCha** [comment]
@matteocrippa Thanks! Will do!

**Comment by thibaultCha** [comment]
Closing this since it is now implemented in TCBlobDownloadSwift, thanks for the suggestions which made me start the new project @albertschulz!
