### ISSUE TITLE
Can download files if app is in background.?

### ISSUE THREAD

**Issue by syrakozz** [thibaultCha/TCBlobDownload#38]
Can download files if app is in background.?

**Comment by tarzon** [comment]
Hi @thibaultCha , i am unable to call the didFinishWithSuccess Delegate method when the application is in Background. Is there a way to update the database(based on download complete) while the application is in background. Currently i am unable to do so.

**Comment by thibaultCha** [comment]
@tarzon You can read more about background execution in the link I provided in my first answer. It also depends on the version of iOS you are developing for.

This library was developed for iOS 5, and back in the day, I used `UIApplication` to create a task that was running in background, and the delegate methods were correctly called. As of today, you probably want to do more reading about it.

Another, probably cleaner solution if you are developing for iOS 7+, is to use [TCBlobDownloadSwift](https://github.com/thibaultCha/TCBlobDownloadSwift) which uses `NSURLSession` for efficient background downloads. The library is not yet entirely completed (missing documentation and you'll need to update the code to use a background session [here](https://github.com/thibaultCha/TCBlobDownloadSwift/blob/master/Source/TCBlobDownloadManager.swift#L43) but already quite usable and very efficient.

**Comment by tarzon** [comment]
Thanx @thibaultCha . I am looking forward to the swift version. Will let you know if that worked for me.
Keep up the great work. :+1:
