### ISSUE TITLE
Thread Management Bug

### ISSUE THREAD

**Issue by EricForGithub** [thibaultCha/TCBlobDownload#41]
Hi, Thanks for your project first. It is good to use, but i've found a thread management bug in the project. As I want to download the files one by one,  I use - (void)setMaxConcurrentDownloads:(NSInteger)maxConcurrent  function and pass 1 as parameter. But after that , the application can only download the first file successfully, which means the rest files won't be download at all!  I looked into your code carefully ,and found a thread management bug. You use  [runLoop run]; to stop the thread from stopping immediately, but never called CFRunLoopStop();  to stop it. That means the thread will never be released. You can call CFRunLoopStop(); to stop the thread in finishOperation(); 
By the way, I tested it on ios8.
Thanks for your wonderful work again.

**Comment by WuKaihei** [comment]
![6f431815-6e49-408b-9add-300e9dfadc24](https://cloud.githubusercontent.com/assets/8187560/8468970/31854a88-20a6-11e5-97eb-908db141ad38.png)
I do not know why this happens，when setMaxConcurrentDownloads is 1.

**Comment by WuKaihei** [comment]
I do not know why this happens，when setMaxConcurrentDownloads is 1.
![ff6a90fc-16b5-498c-8bfc-1a8376481c16](https://cloud.githubusercontent.com/assets/8187560/8469046/04e5d302-20a7-11e5-994b-bd018d975945.png)
