### ISSUE TITLE
Can not multi download and direct link

### ISSUE THREAD

**Issue by letien91** [thibaultCha/TCBlobDownload#52]
I run the simple, but multi download is not work. And direct link, look like: 
"http://r1---sn-po4vgh5upj5-jfce.googlevideo.com/videoplayback?mv=m&expire=1428094697&source=youtube&ratebypass=yes&ms=au&dur=4781.058&sver=3&mt=1428072973&pl=21&id=o-APnvgRVyGg04p6Po52EA5L_BMKQoSiW20stnHoSLea-B&initcwndbps=813750&fexp=900720%2C906220%2C907263%2C923367%2C924619%2C931358%2C934954%2C9406895%2C9407840%2C9408046%2C9408102%2C9408687%2C947243%2C948124%2C948603%2C948703%2C948913%2C949432%2C951703%2C952612%2C957201%2C961404%2C961406&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Csource%2Cupn%2Cexpire&upn=BmaCN10tdsE&itag=22&ipbits=0&mm=31&ip=200.17.101.37&key=yt5&signature=4C66B4C3FFB8711D3474FE70F5DD65A1EFA4B0B7.D806F1F13DFA711D1F38A7F26CBF668ED2433BC8&title=Illusions+by+Thomas+Bergersen" (i got it from youtube) is not work, too.

**Comment by thibaultCha** [comment]
I just tried your link in the example app, and was able to downlaod the file. I also tried the multiple downloads example (that I didn't write), it also worked.

I cannot help without more details/steps to reproduce/code examples.

**Comment by letien91** [comment]
Sorry, my bad.
