### ISSUE TITLE
Download in the background process

### ISSUE THREAD

**Issue by khaledannajar** [thibaultCha/TCBlobDownload#65]
If the user locked the screen the download is stopped. When I searched about it I found in Apple's documentation it recommends using NSURLSession instead of NSURLConnection here [apple docs](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW5). 

Is there a way to prevent the download from stopping when the app enters background. Or do I have to edit the implementation and use NSURLSession.

**Comment by thibaultCha** [comment]
Hi,

This library was developed prior to the implementation of NSURLSession. See https://github.com/thibaultCha/TCBlobDownloadSwift for an implementation using NSURLSession. Als see #38 for a similar question.

**Comment by khaledannajar** [comment]
Thanks. I am going to check it.

**Comment by khaledannajar** [comment]
I used this code in [Apple Docs] (https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW5) as you suggested and it works fine.
